// This file is automatically generated. Do not modify it manually.
// This file is used to generate the firebase-config.js file.
// If you need to change the configuration, please edit docs/backend.json.
//
// For more information, see:
// https://firebase.google.com/docs/web/learn-more#config-object
//
// This object is used to initialize the Firebase app in the browser.
export const firebaseConfig = {
  "projectId": "studio-770359382-db111",
  "appId": "1:79648401698:web:31030f0df29820dbe2dd7b",
  "apiKey": "AIzaSyASjQkpCYnbsS_csgCdWbnrWk27Q9m7sOo",
  "authDomain": "studio-770359382-db111.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "79648401698",
  "storageBucket": "studio-770359382-db111.appspot.com"
};
