// This file is automatically generated. Do not modify it manually.
// This file is used to generate the firebase-config.js file.
// If you need to change the configuration, please edit docs/backend.json.
//
// For more information, see:
// https://firebase.google.com/docs/web/learn-more#config-object
//
// This object is used to initialize the Firebase app in the browser.
export const firebaseConfig = {
  "projectId": "studio-770359382-db111",
  "appId": "1:79648401698:web:75a7c2b535d519bce2dd7b",
  "apiKey": "AIzaSyDF18Jii8SgRDb0n8GjI0G1g2-lT_9qCew",
  "authDomain": "studio-770359382-db111.firebaseapp.com",
  "measurementId": "G-49VS0LFW6K",
  "messagingSenderId": "79648401698",
  "storageBucket": "studio-770359382-db111.appspot.com"
};
