'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useLocalStorage } from '@/hooks/use-local-storage';
import { Button } from '@/components/ui/button';
import { Header } from '@/components/header';
import { ArrowLeft, Loader2 } from 'lucide-react';

type PaperDetails = {
    class: string;
    subject: string;
    board: string;
    chapter: string;
};

export default function PaperPage() {
    const router = useRouter();
    const [generatedPaper] = useLocalStorage<string | null>('generatedPaper', null);
    const [paperDetails] = useLocalStorage<PaperDetails | null>('paperDetails', null);
    const [isClient, setIsClient] = useState(false);

    useEffect(() => {
        setIsClient(true);
    }, []);
    
    useEffect(() => {
        if (isClient && !generatedPaper) {
            router.replace('/most-expected-questions');
        }
    }, [isClient, generatedPaper, router]);

    if (!isClient || !generatedPaper || !paperDetails) {
        return (
             <div className="flex h-screen w-full items-center justify-center">
                <Loader2 className="h-8 w-8 animate-spin" />
            </div>
        );
    }

    return (
        <div className="flex flex-col bg-muted/20 min-h-screen">
            <Header title="Generated Question Paper" />
            <main className="flex-1 p-4 md:p-8">
                <Button variant="ghost" onClick={() => router.push('/most-expected-questions')} className="mb-4">
                    <ArrowLeft className="mr-2 h-4 w-4" /> Back to Generator
                </Button>
                
                <div className="bg-white max-w-4xl mx-auto p-8 border rounded-lg shadow-lg">
                    <div className="text-center mb-6">
                        <p className="font-bold text-red-600">
                            MOST EXPECTED QUESTIONS
                        </p>
                        <h1 className="text-2xl font-bold mt-1">
                            {paperDetails.board} - {paperDetails.class}
                        </h1>
                        <p className="text-lg font-semibold">{paperDetails.subject}{paperDetails.chapter ? ` - ${paperDetails.chapter}`: ''}</p>
                    </div>

                    <div className="text-left text-sm mb-8 p-4 border border-dashed rounded-md">
                        <h3 className="font-bold text-red-600 border-b-2 border-red-600 pb-1 inline-block mb-2">IMPORTANT INSTRUCTIONS:</h3>
                        <ul className="list-disc list-inside space-y-1">
                            <li>These questions are generated by AI based on exam trends and important topics.</li>
                            <li>They are intended for practice and to highlight key areas of study.</li>
                            <li>This is not a prediction of the actual exam paper.</li>
                        </ul>
                    </div>

                    <div className="prose prose-sm max-w-none whitespace-pre-wrap font-sans">
                      {generatedPaper.split('\n').map((line, index) => {
                          if (line.startsWith('### ')) {
                              return <h3 key={index} className="font-bold text-lg bg-gray-200 p-2 rounded-md my-4 text-center">{line.replace('### ', '')}</h3>
                          }
                          if (line.startsWith('**This list')) {
                              const cleanLine = line.replace(/\*/g, '');
                              return <p key={index} className="text-center font-bold text-muted-foreground mt-8">{cleanLine}</p>
                          }
                           if (line.startsWith('**Ans.**')) {
                              return <p key={index} className="!my-1"><strong className="text-green-700">{line.substring(0, 7)}</strong>{line.substring(7)}</p>
                          }
                           if (line.startsWith('**Sol.**')) {
                              return <p key={index} className="!my-1"><strong className="text-blue-700">{line.substring(0, 7)}</strong>{line.substring(7)}</p>
                          }
                          return <p key={index} className="!my-2">{line}</p>
                      })}
                    </div>
                </div>
            </main>
        </div>
    );
}
